name: Push Notification

on:
  schedule:
    - cron: '0 12 * * *' # todos os dias ao meio-dia UTC

jobs:
  send-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install web-push @supabase/supabase-js node-fetch
      - run: node backend/sendPush.js verse
        env:
          # Coloque suas variáveis sensíveis como secrets no GitHub!
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          VITE_BIBLIA_API_TOKEN: ${{ secrets.VITE_BIBLIA_API_TOKEN }}
